Updates bignum dependency to work on latest Node.js/iojs
The bignum 0.6 doesn't work on latest iojs (3.0.0), soon to be Node.js (4.0.0). This is due to some breaking changes on v8 internals.

```
../bignum.cc:205:36: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
  static Handle<Value> Bpowm(const Arguments& args);
                                   ^~~~~~~~~
                                   v8::internal::Arguments
```

I've also added a repository link so that npm knows how to point here